main: me.stefvanschie.buildinggame.Main
version: 1.9.6
name: BuildingGame
authors: [stefvanschie]
commands:
  bg:
    description: Main buildinggame command
  buildinggame:
    description: Main buildinggame command
