main: com.gmail.stefvanschiedev.buildinggame.Main
version: 1.12.3
name: BuildingGame
author: stefvanschie
commands:
  bg:
    description: Main buildinggame command
  buildinggame:
    description: Main buildinggame command