name: BuildingGame
main: me.stefvanschie.BuildingGame
version: 1.0.1
authors: [stefvanschie]
commands:
  bg:
    description: BuildingGame command
  buildinggame:
    description: BuildingGame command
